export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_POST = 'ADD_POST'
export const DELETE_COMMENT = 'DELETE_COMMENT'
export const DELETE_POST = 'DELETE_POST'
export const EDIT_POST = 'EDIT_POST'
export const EDIT_COMMENT = 'EDIT_COMMENT'
export const GET_ALL_COMMENTS = 'GET_ALL_COMMENTS'
export const GET_ALL_CATEGORIES = 'GET_ALL_CATEGORIES'
export const GET_ALL_POSTS = 'GET_ALL_POSTS'
export const GET_POSTS_FOR_CATEGORY = 'GET_POSTS_FOR_CATEGORY'
export const SELECT_COMMENT = 'SELECT_COMMENT'
export const SELECT_POST = 'SELECT_POST'
export const SELECT_CATEGORY = 'SELECT_CATEGORY'
export const VOTE_ON_POST = 'VOTE_ON_POST'
export const VOTE_ON_COMMENT = 'VOTE_ON_COMMENT'

export const LOAD_CATEGORIES = 'LOAD_CATEGORIES'
export const LOAD_POSTS = 'LOAD_POSTS'
export const LOAD_CATEGORY_POSTS = 'LOAD_CATEGORY_POSTS'

export const LOAD_POST = 'LOAD_POST'

export const CREATE_POST = 'CREATE_POST'

export const LOAD_COMMENTS = 'LOAD_COMMENTS'

export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_POST = 'FETCH_POST'
